title: Blog do Marce1in
description: >-
  Welcome to my blog! The objective of this blog is to just post
  about things I have been doing or things that I think are cool
  to write about, mostly Technology stuff.
github_username: Marce1in
url: "https://blog.marce1in.com.br"
author: Marcelo Oscaberry

# Localization
languages: ["en", "pt-BR"]
default_lang: "pt-BR"
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap"]
parallel_localization: true

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-date-localization
  - jekyll-minifier
